export { Hero } from './Hero'
export { Stats } from './Stats'
export { Services } from './Services'
export { About } from './About'
export { Projects } from './Projects'
export { News } from './News'
